import os

import openai
from dotenv import load_dotenv

from logs.logging import logger

load_dotenv()

# Check for required environment variables
if "OPENAI_ORGANIZATION" not in os.environ or "OPENAI_API_KEY" not in os.environ:
    raise ValueError(
        "Missing OpenAI environment variables. Please set OPENAI_ORGANIZATION and OPENAI_API_KEY."
    )

openai.organization = os.getenv("OPENAI_ORGANIZATION")
openai.api_key = os.getenv("OPENAI_API_KEY")

# Constants for system messages
TEXT_SYSTEM_MESSAGE = "I want you to act as a spoken English teacher and improver. I will speak to you in English, and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the response to 100 words. I want you to strictly correct my grammar mistakes, typos, and factual errors. I want you to ask me a question in your reply."
VOICE_SYSTEM_MESSAGE = "I want you to act as a spoken English teacher and improver. I'll transcribe your message and ask for corrections in speaking-related issues, excluding pronunciation. Please focus on improving fluency, expression, and other spoken aspects. Keep your response under 100 words and include a question for interactive practice."


def process_text_interaction(user_input: str, model: str = "gpt-3.5-turbo") -> str:
    """
    Handles the interaction when users communicate through text messages.

    Args:
    - user_input (str): The user's input.
    - model (str): The OpenAI model to use (default is "gpt-3.5-turbo").

    Returns:
    - str: The response generated by the ChatGPT model.
    """
    try:
        if not user_input.strip():
            logger.warning("Empty user input received.")
            return "Please provide a non-empty user input."

        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": TEXT_SYSTEM_MESSAGE},
                {"role": "user", "content": user_input},
            ],
        )
        response_content = response["choices"][0].get("message", {}).get("content", "")
        return response_content

    except Exception as e:
        logger.error(f"An error occurred: {e}")


def process_voice_interaction(user_input: str, model: str = "gpt-3.5-turbo") -> str:
    """
    Manages the interaction when users communicate through voice messages,
    including transcription and spoken-related corrections.

    Args:
    - user_input (str): The user's input.
    - model (str): The OpenAI model to use (default is "gpt-3.5-turbo").

    Returns:
    - str: The response generated by the ChatGPT model.
    """
    try:
        if not user_input.strip():
            logger.warning("Empty user input received.")
            return "Please provide a non-empty user input."

        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": VOICE_SYSTEM_MESSAGE},
                {"role": "user", "content": user_input},
            ],
        )
        response_content = response["choices"][0].get("message", {}).get("content", "")
        return response_content

    except Exception as e:
        logger.error(f"An error occurred: {e}")
